# Basic Information 
title: Song Yin
position: Ph.D. candidate
affiliation: University of Illinois Urbana-Champaign (UIUC)
affiliation_link: https://illinois.edu/
affiliation_logo: ./assets/img/illinois.svg
email: songyin2 (at) illinois.edu

# Search Engine Optimization (SEO)
keywords: Song Yin, Yin Song, songyin, yinsong
canonical: https://shuklagroup.org/people/song-yin/
description: Song Yin is a Ph.D. candidate at University of Illinois Urbana Champaign (UIUC).

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=68gaRMoAAAAJ&hl=en
github_link: https://github.com/songyingit
linkedin: https://linkedin.com/in/songyin

# Images 
avatar: ./assets/img/songyin.jpg
favicon: ./assets/img/Block-I-orange-white-background.png
favicon_dark: ./assets/img/Block-I-orange-blue-background.png

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
  - vendor